- name: Send mail
  on: [push]
  uses: dawidd6/action-send-mail@v2
  with:
    server_address: smtp.gmail.com
    server_port: 465
    username: ${{secrets.MAIL_USERNAME}}
    password: ${{secrets.MAIL_PASSWORD}}
    subject: Github Actions job result
    # Literal body:
    body: Commit has been successfully pushed to ${{github.repository}}!
    # Read file contents as body:
    body: file://README.md
    to: myfavgitrepo@gmail.com
    from: MyFavGitRepo # <user@example.com>
    # Optional content type (defaults to text/plain):
    content_type: text/html
    # Optional attachments:
    attachments: attachments.zip,git.diff,./dist/static/main.js
