name: build-and-push to docker

on:
  release:
    types: [published]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      -
        name: Docker Build
        uses: docker/build-push-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
