name: build-and-push to docker

on: push

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      -
        name: Docker Build
        uses: docker/build-push-action@v1.1.1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: devops_project
          dockerfile: devops_project/Dockerfile
